- name: "demo on variables"
  hosts: localhost
  connection: local
  vars:
    COURSE: "Ansible"
    TRAINER: "shiva"
    DURATION: "150hrs"
  tasks:
  - debug:
      msg: "HI learning {{ COURSE }}, trainer is {{ TRAINER }}, Duration is {{ DURATION }}"