- name: "demo on task level variables"
  hosts: localhost
  connection: local
  vars:
    COURSE: "Ansible"
    TRAINER: "shiva"
    DURATION: "150hrs"
  tasks:
  - name: "Print information"
    vars: 
      COURSE: "DevSecOps with AIOps"
    debug:
      msg: "HI learning {{ COURSE }}, trainer is {{ TRAINER }}, Duration is {{ DURATION }}"