- name: Demo on filters
  hosts: local
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
  tasks:
  - name: Conver string to list
    debug:
      msg: "Topics are: {{ topics | split(',') }}"
  
  - name: "Set default values"
    debug:
      msg: "HI {{ GREETING | default('Good morning')}}"