- name: "Install and start nginx"
  hosts: frontend
  become: yes
  tasks:
  - name: "Installing nginx"
    ansible.builtin.package: 
      name: "install"
      state: present
  - name: "Start nginx"
    service:
      name: 'install'
      state: "started"
      enabled: yes
