- name: "Demo on variables"
  hosts: localhost
  connection: local
  vars:
    COURSE: 'Ansible'
    TRAINER: 'siva'
    DURATION: '150px'
  tasks: 
  - debug:
      msg: "Hi Learning {{COURSE}}, trainer is {{TRAINER}}. Duration is {{DURATION}}"
